name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish PowerShell
        uses: natescherer/publish-powershell-action@v1.1.1
        with:
          token: ${{ secrets.GALLERY_API_KEY }}
          target: gallery
          path: ClickUpAPI
